--LAB 4
-- 1
DROP TABLE FIGURY
CREATE TABLE FIGURY(
ID number(1),
KSZTALT MDSYS.SDO_GEOMETRY
);s

INSERT INTO FIGURY VALUES (
1, MDSYS.SDO_GEOMETRY(2003,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,4),
SDO_ORDINATE_ARRAY(3,5,5,7,7,5) )

)


INSERT INTO FIGURY VALUES (
2, MDSYS.SDO_GEOMETRY(2003,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,3),
SDO_ORDINATE_ARRAY(1,1,5,5) )

)
SELECT * FROM FIGURY


INSERT INTO FIGURY VALUES (
3, MDSYS.SDO_GEOMETRY(2002,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2),
SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1) )

)

INSERT INTO FIGURY VALUES (
4, MDSYS.SDO_GEOMETRY(2003,NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,4),
SDO_ORDINATE_ARRAY(3,5,7,5,5,5,5,7) )

)

SELECT * FROM FIGURY

select SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT,0.01) FROM FIGURY

DELETE FROM FIGURY WHERE ID=4

COMMIT


--------------------------------------------------------------------------

--LAB 5
--1
--A


SELECT * FROM USER_SDO_GEOM_METADATA

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='FIGURY'

INSERT INTO USER_SDO_GEOM_METADATA
VALUES (
'FIGURY',
'KSZTALT',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('DL',0,10,0.01),
MDSYS.SDO_DIM_ELEMENT('SZER',0,10,0.01) ),
NULL
);

--B
SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000,8192,10,2,0) FROM FIGURY


--C

SELECT  *
FROM    all_indexes
WHERE   table_name = 'FIGURY';

DROP INDEX FIGURY_IDXX;

create index FIGURY_IDXX
on FIGURY(KSZTALT)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

--D
select ID
from FIGURY
where SDO_FILTER(KSZTALT,
SDO_GEOMETRY(2001,null, 
SDO_POINT_TYPE(3,3,null), null,null)) = 'TRUE';

--E
select ID
from FIGURY
where SDO_RELATE(KSZTALT,
SDO_GEOMETRY(2001,null,
SDO_POINT_TYPE(3,3,null),null,null), 'mask=ANYINTERACT') = 'TRUE';

--------------------------------------------------------------------

--------------------------------------------------------------------------

--LAB 5
--1
--A


SELECT * FROM USER_SDO_GEOM_METADATA

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='FIGURY'

INSERT INTO USER_SDO_GEOM_METADATA
VALUES (
'FIGURY',
'KSZTALT',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('DL',0,10,0.01),
MDSYS.SDO_DIM_ELEMENT('SZER',0,10,0.01) ),
NULL
);

--B
SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000,8192,10,2,0) FROM FIGURY

--C

SELECT  *
FROM    all_indexes
WHERE   table_name = 'FIGURY';

DROP INDEX FIGURY_IDXX;

create index FIGURY_IDXX
on FIGURY(KSZTALT)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

--D
select ID
from FIGURY
where SDO_FILTER(KSZTALT,
SDO_GEOMETRY(2001,null,
SDO_POINT_TYPE(3,3,null), null,null)) = 'TRUE';

--E
select ID
from FIGURY
where SDO_RELATE(KSZTALT,
SDO_GEOMETRY(2001,null,
SDO_POINT_TYPE(3,3,null),null,null), 'mask=ANYINTERACT') = 'TRUE';

-------------------------------------------------------------------------------------------------
--LAB 5
select * from MAJOR_CITIES
select GEOM from MAJOR_CITIES where CITY_NAME='Warsaw'
-- A

select A.CITY_NAME, ROUND(SDO_NN_DISTANCE(1)) DISTANCE
from MAJOR_CITIES A
where SDO_NN(GEOM,
(select GEOM from MAJOR_CITIES where CITY_NAME='Warsaw' )
,
'sdo_num_res=10 unit=km',1) = 'TRUE' AND CITY_NAME not like 'Warsaw';

--B

select C.CITY_NAME
from MAJOR_CITIES C
where SDO_WITHIN_DISTANCE(C.GEOM,
(select GEOM from MAJOR_CITIES where CITY_NAME='Warsaw' ),
'distance=100 unit=km') = 'TRUE' AND C.CITY_NAME not like'Warsaw';

--C
select * from MAJOR_CITIES where CNTRY_NAME='Slovakia'

select C.CNTRY_NAME, C.CITY_NAME
FROM MAJOR_CITIES C
WHERE SDO_GEOM.RELATE
(
    C.GEOM, 'ANYINTERACT',
    (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME = 'Slovakia')
) = 'TRUE'

-- D

SELECT B.CNTRY_NAME, SDO_GEOM.SDO_DISTANCE(A.GEOM, B.GEOM, 1, 'unit=km')
FROM COUNTRY_BOUNDARIES A, COUNTRY_BOUNDARIES B
WHERE A.CNTRY_NAME='Poland'
AND 
SDO_RELATE(A.GEOM, B.GEOM, 'mask=TOUCH') != 'TRUE' AND B.CNTRY_NAME!='Poland';

--3
--A
select A.CNTRY_NAME,
B.CNTRY_NAME,
ROUND(SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, B.GEOM, 1), 1, 'unit=km'))
from COUNTRY_BOUNDARIES A,
COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = 'Poland'
and SDO_RELATE(A.GEOM, B.GEOM, 'mask=touch') ='TRUE';

-- B
select A.CNTRY_NAME,
ROUND(SDO_GEOM.sdo_area(A.GEOM, 1, 'unit=SQ_KM')) POWIERZCHNIA
from COUNTRY_BOUNDARIES A
order by 1 desc

-- C 

select * from MAJOR_CITIES where CITY_NAME='Lodz'

select SDO_GEOM.SDO_AREA(
 SDO_GEOM.SDO_MBR(A.GEOM))
from MAJOR_CITIES A
where A.CITY_NAME IN ('Warsaw', 'Lodz');

-- D

select SDO_GEOM.SDO_UNION(
(select GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME='Poland'), 
(select GEOM FROM MAJOR_CITIES WHERE CITY_NAME='Prague')).GET_GTYPE() FROM DUAL;

-- E

select A.CITY_NAME, B.CNTRY_NAME
from MAJOR_CITIES A, COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = B.CNTRY_NAME
and
SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(B.GEOM,1), A.GEOM,1) = 
(SELECT MIN(SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(B.GEOM,1), A.GEOM,1))
from MAJOR_CITIES A, COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = B.CNTRY_NAME);

-- F

select  NAME,
SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, B.GEOM, 1), 1, 'unit=km') AS DLUGOSC
from COUNTRY_BOUNDARIES A, RIVERS B
where A.CNTRY_NAME = 'Poland' AND
SDO_RELATE(A.GEOM, B.GEOM, 'MASK=OVERLAPBDYINTERSECT')='TRUE';

SELECT * FROM COUNTRY_BOUNDARIES
SELECT * FROM  MAJOR_CITIES
SELECT * FROM STREETS_AND_RAILROADS
SELECT * FROM  WATER_BODIES
SELECT * FROM  RIVERS
